email: tanya@releasewellnessca.com
phone: (949) 687-3899
address_line1: 324 Avenida de La Estrella, Suite B
address_line2: San Clemente, CA 92672
psychology_today_url: https://www.psychologytoday.com/us/therapists/tanya-l-hauer-san-clemente-ca/1741342
instagram_url: https://www.instagram.com/releasewellnessca/
facebook_url: https://www.facebook.com/releasewellnessca/
